### ISSUE TITLE
PlayerListActivity.java line 92

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#217]
#### in uk.org.ngo.squeezer.itemlist.PlayerListActivity.onCreate

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58e381500aeb16625b3a1010](https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58e381500aeb16625b3a1010)

**Comment by nikclayton** [comment]
In 1.4.1, stack trace is:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.org.ngo.squeezer/uk.org.ngo.squeezer.itemlist.PlayerListActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2049)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2083)
       at android.app.ActivityThread.access$600(ActivityThread.java:134)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4697)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at uk.org.ngo.squeezer.itemlist.PlayerListActivity.onCreate(PlayerListActivity.java:92)
       at android.app.Activity.performCreate(Activity.java:4539)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2013)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2083)
       at android.app.ActivityThread.access$600(ActivityThread.java:134)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4697)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
