### ISSUE TITLE
ScanNetworkTask.java line 196

### ISSUE THREAD

**Issue by nikclayton** [nikclayton/android-squeezer#226]
#### in uk.org.ngo.squeezer.util.ScanNetworkTask.extractNameFromBuffer

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58ed42aa0aeb16625b8c52ea](https://fabric.io/squeezer/android/apps/uk.org.ngo.squeezer/issues/58ed42aa0aeb16625b8c52ea)

**Comment by nikclayton** [comment]
Stack trace:

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by java.lang.StringIndexOutOfBoundsException: length=512; regionStart=6; regionLength=-28
       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
       at uk.org.ngo.squeezer.util.ScanNetworkTask.extractNameFromBuffer(ScanNetworkTask.java:196)
       at uk.org.ngo.squeezer.util.ScanNetworkTask.doInBackground(ScanNetworkTask.java:116)
       at uk.org.ngo.squeezer.util.ScanNetworkTask.doInBackground(ScanNetworkTask.java:23)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```
